# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data_entry_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_recorded', models.DateField(verbose_name='%Y-%m-%d')),
                ('time_recorded', models.TimeField(verbose_name='%H:%M:%S')),
                ('average', models.FloatField(blank=True, default=None, null=True)),
                ('original_file', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'acoustic_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('site_id', models.TextField(primary_key=True, serialize=False)),
                ('site_name', models.TextField(max_length=255)),
                ('id', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'site',
                'managed': False,
            },
        ),
    ]
